//
export const Weapons: { [name: string]: string } = {
    ".52ガロン": "52 Gal",
    ".96ガロン": "96 Gal",
    ".96ガロンデコ": "96 Gal Deco",
    プロモデラーRG: "Aerospray MG",
    プロモデラーMG: "Aerospray RG",
    クーゲルシュライバー: "Ballpoint Splatling",
    "14式竹筒銃・甲": "Bamboozler 14 Mk I",
    ワイドローラー: "Big Swig Roller",
    ホットブラスター: "Blaster",
    オーバーフロッシャー: "Bloblobber",
    カーボンローラー: "Carbon Roller",
    カーボンローラーデコ: "Carbon Roller Deco",
    クラッシュブラスター: "Clash Blaster",
    スクイックリンα: "Classic Squiffer",
    ジェットスイーパーカスタム: "Custom Jet Squelcher",
    もみじシューター: "Custom Splattershot Jr.",
    スパッタリー: "Dapple Dualies",
    "スパッタリー・ヒュー": "Dapple Dualies Nouveau",
    クアッドホッパーブラック: "Dark Tetra Dualies",
    デュアルスイーパー: "Dualie Squelchers",
    ダイナモローラー: "Dynamo Roller",
    リッター4K: "E-liter 4K",
    "4Kスコープ": "E-liter 4K Scope",
    エクスプロッシャー: "Explosher",
    ヴァリアブルローラー: "Flingza Roller",
    プライムシューターコラボ: "Forge Splattershot Pro",
    ケルビン525: "Glooga Dualies",
    ソイチューバー: "Goo Tuber",
    H3リールガン: "H-3 Nozzlenose",
    バレルスピナー: "Heavy Splatling",
    ヒーローシューターレプリカ: "Hero Shot Replica",
    ハイドラント: "Hydra Splatling",
    パブロ: "Inkbrush",
    "パブロ・ヒュー": "Inkbrush Nouveau",
    ジェットスイーパー: "Jet Squelcher",
    スプラローラーコラボ: "Krak-On Splat Roller",
    L3リールガン: "L-3 Nozzlenose",
    L3リールガンD: "L-3 Nozzlenose D",
    ノヴァブラスター: "Luna Blaster",
    ノヴァブラスターネオ: "Luna Blaster Neo",
    スプラスピナー: "Mini Splatling",
    "N-ZAP85": "N-ZAP '85",
    "N-ZAP89": "N-ZAP '89",
    ノーチラス47: "Nautilus 47",
    シャープマーカーネオ: "Neo Splash-o-matic",
    ボールドマーカーネオ: "Neo Sploosh-o-matic",
    ホクサイ: "Octobrush",
    ロングブラスター: "Range Blaster",
    ラピッドブラスター: "Rapid Blaster",
    ラピッドブラスターデコ: "Rapid Blaster Deco",
    Rブラスターエリート: "Rapid Blaster Pro",
    LACT450: "REEF-LUX 450",
    バケットスロッシャー: "Slosher",
    バケットスロッシャーデコ: "Slosher Deco",
    スクリュースロッシャー: "Sloshing Machine",
    "R-PEN/5H": "Snipewriter 5H",
    シャープマーカー: "Splash-o-matic",
    パラシェルター: "Splat Brella",
    スプラチャージャー: "Splat Charger",
    スプラマニューバー: "Splat Dualies",
    スプラローラー: "Splat Roller",
    ジムワイパー: "Splatana Stamper",
    ドライブワイパー: "Splatana Wiper",
    スプラスコープ: "Splatterscope",
    スプラシューター: "Splattershot",
    わかばシューター: "Splattershot Jr.",
    スペースシューター: "Splattershot Nova",
    プライムシューター: "Splattershot Pro",
    ボールドマーカー: "Sploosh-o-matic",
    ボトルガイザー: "Squeezer",
    キャンピングシェルター: "Tenta Brella",
    スプラシューターコラボ: "Tentatek Splattershot",
    ヒッセン: "Tri-Slosher",
    "ヒッセン・ヒュー": "Tri-Slosher Nouveau",
    トライストリンガー: "Tri-Stringer",
    スパイガジェット: "Undercover Brella",
    スプラチャージャーコラボ: "Z+F Splat Charger",
    スプラスコープコラボ: "Z+F Splatterscope",
    スプラスピナーコラボ: "Zink Mini Splatling",
};
